-- ============================================================================
-- 1. SOCIAL PLATFORMS CONFIGURATION & CREDENTIALS AUDIT MAP
-- ============================================================================
CREATE TABLE platform_accounts (
    account_id INTEGER PRIMARY KEY AUTOINCREMENT,
    platform_name TEXT NOT NULL,              -- 'twitter', 'linkedin', 'tiktok', 'instagram'
    account_handle TEXT NOT NULL,             -- Username or display handle
    is_active INTEGER DEFAULT 1,              -- 1 = Connected and Valid, 0 = Token Expired/Revoked
    last_authenticated_at TEXT DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(platform_name, account_handle)
);

-- ============================================================================
-- 2. CONTENT QUEUE & BROADCAST HISTORY TABLE
-- ============================================================================
CREATE TABLE broadcast_posts (
    post_id TEXT PRIMARY KEY,                 -- Local system verification unique identifier
    content_message TEXT NOT NULL,            -- Main caption/text payload string
    has_media INTEGER DEFAULT 0,              -- 1 = Contains images/video files, 0 = Plain Text Only
    media_url TEXT NULL,                      -- Path to the file hosted locally or via static bucket
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- 3. INTERFACE DEEP RUNTIME TELEMETRY LOGS (OBSERVABILITY)
-- ============================================================================
CREATE TABLE api_execution_logs (
    log_id INTEGER PRIMARY KEY AUTOINCREMENT,
    post_id TEXT NOT NULL,
    platform_name TEXT NOT NULL,              -- Target platform for individual tracking metric
    status TEXT NOT NULL,                     -- 'QUEUED', 'SUCCESS', 'FAILED'
    response_code INTEGER NULL,               -- HTTP response status returned by platform endpoint (e.g., 200, 201, 401)
    remote_post_id TEXT NULL,                 -- Post identifier generated by external API (e.g., Twitter ID string)
    error_message TEXT NULL,                  -- Holds specific API exception details or stack traces on breakdown
    executed_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (post_id) REFERENCES broadcast_posts(post_id) ON DELETE CASCADE
);
